# Generated by Django 4.2.7 on 2024-03-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userid',
        ),
    ]
