# Generated by Django 4.2.7 on 2024-03-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_items_menu_rename_username_userprofile_user_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
