# Generated by Django 4.2.7 on 2024-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu',
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ManyToManyField(related_name='orders', to='main.menu'),
        ),
    ]
