# Generated by Django 4.2.7 on 2024-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_menu_item_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item',
            field=models.ManyToManyField(to='main.item'),
        ),
    ]
